#!/bin/bash

read -p "Choose 'packer' or 'lazy' package manager (lazy is default): " choice

HOME_DIR="$HOME"
BAK_DIR="${HOME_DIR}/.config/nvim/lua/core/bak"
DEST_FILE="${HOME_DIR}/.config/nvim/lua/core/plugins.lua"

# Remove directories and files if they exist
if [ -d "${HOME_DIR}/.local/state/nvim" ]; then
  echo "Deleting ${HOME_DIR}/.local/state/nvim"
  rm -rf "${HOME_DIR}/.local/state/nvim"
fi

if [ -d "${HOME_DIR}/.local/share/nvim" ]; then
  echo "Deleting ${HOME_DIR}/.local/share/nvim"
  rm -rf "${HOME_DIR}/.local/share/nvim"
fi

for json_file in "${HOME_DIR}/.config/nvim/"*.json; do
  if [ -f "$json_file" ]; then
    echo "Deleting ${HOME_DIR}/.config/nvim/*json"
    rm -f "$json_file"
  fi
done

if [ -f "${HOME_DIR}/.config/nvim/lua/core/plugins.lua" ]; then
  echo "Deleting ${HOME_DIR}/.config/nvim/lua/core/plugins.lua"
  rm -rf "${HOME_DIR}/.config/nvim/lua/core/plugins.lua"
fi

if [ -d "${HOME_DIR}/.config/nvim/plugin" ]; then
  echo "Deleting ${HOME_DIR}/.config/nvim/plugin"
  rm -rf "${HOME_DIR}/.config/nvim/plugin"
fi

# Copy plugins.lua files
if [ "$choice" == "packer" ]; then
  echo "Copying ${BAK_DIR}/packer_plugins.lua"
  cp "${BAK_DIR}/packer_plugins.lua" "$DEST_FILE"
else
  echo "Copying ${BAK_DIR}/lazy_plugins.lua"
  cp "${BAK_DIR}/lazy_plugins.lua" "$DEST_FILE"
fi

echo "Done"

